name: flutter_appwrite_starter
description: Complete starter template for Flutter + Appwrite projects
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crop_your_image: ^1.0.2
  device_info_plus: ^9.1.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  appwrite: ^11.0.1
  file: ^7.0.0
  go_router: ^13.2.2
  get_it: ^7.6.7
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  rename: ^3.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
