name: flutter_appwrite_starter
description: Complete starter template for Flutter + Appwrite projects
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  appwrite_auth_kit: ^0.8.0
  crop: ^0.5.5
  crop_your_image: ^0.7.4
  device_info_plus: ^8.1.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  package_info_plus: ^3.0.3
  path_provider: ^2.0.15
  appwrite: ^9.0.0
  file: ^6.1.4
  go_router: ^7.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  rename: ^2.1.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
